apiVersion: v1
kind: Service
metadata:
  labels:
    app: statichttpserver1
  name: statichttpserver1
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: statichttpserver1
