apiVersion: v1
kind: Service
metadata:
  labels:
    app: statichttpserver2
  name: statichttpserver2
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: statichttpserver2
