apiVersion: v1
kind: Service
metadata:
  labels:
    app: statichttpserver3
  name: statichttpserver3
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: statichttpserver3
